# Generated by Django 5.2 on 2025-04-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_verify_code_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Код верификации!'),
        ),
    ]
