# Generated by Django 5.2.1 on 2025-05-21 14:21

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_verify_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Номер телефона",
            ),
        ),
    ]
