# Generated by Django 5.2.1 on 2025-05-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_country_alter_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verify_code",
        ),
        migrations.AddField(
            model_name="user",
            name="is_verifed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
