# Generated by Django 5.2.1 on 2025-05-22 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_user_verify_code_user_is_verifed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_verifed",
            new_name="is_verified",
        ),
    ]
