# Generated by Django 5.2 on 2025-04-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_client_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="Ф.И.О"),
        ),
    ]
