# Generated by Django 5.2 on 2025-04-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_messages', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['message_subject'], 'permissions': [('can_view_message', 'Can view message')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
