# Generated by Django 5.2 on 2025-04-07 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('mail_messages', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название рассылки')),
                ('start_date_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время первой отправки')),
                ('end_date_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время окончания отправки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], db_index=True, default='created', max_length=25, verbose_name='Статус')),
                ('clients', models.ManyToManyField(related_name='mailings', to='clients.client', verbose_name='Клиенты')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mail_messages.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
