# Generated by Django 5.2.1 on 2025-05-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_date_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время окончания отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_date_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время первой отправки"
            ),
        ),
    ]
